import type { Agent, Conversation, Message } from "@/types"

export const mockAgents: Agent[] = [
  {
    id: "xm",
    name: "小明",
    role: "产品分析师",
    avatar: "XM",
    skills: ["市场研究", "竞品分析", "产品策略", "数据解读"],
    category: "分析与策略",
    status: "working",
    currentTask: "分析 Q3 用户增长数据",
    taskProgress: 72,
    lastActiveAt: "2 分钟前",
  },
  {
    id: "xh",
    name: "小红",
    role: "文案专家",
    avatar: "XH",
    skills: ["营销文案", "品牌故事", "社交媒体", "内容策划"],
    category: "内容与创意",
    status: "idle",
    lastActiveAt: "5 分钟前",
  },
  {
    id: "xl",
    name: "小李",
    role: "数据专家",
    avatar: "XL",
    skills: ["数据分析", "报表", "可视化", "SQL"],
    category: "数据与运营",
    status: "working",
    currentTask: "绘制产品原型",
    taskProgress: 35,
    lastActiveAt: "1 分钟前",
  },
  {
    id: "xw",
    name: "小薇",
    role: "排期专员",
    avatar: "XW",
    skills: ["项目排期", "进度跟踪", "资源协调"],
    category: "数据与运营",
    status: "idle",
    lastActiveAt: "10 分钟前",
  },
  {
    id: "xz",
    name: "小智",
    role: "策略顾问",
    avatar: "XZ",
    skills: ["商业规划", "增长策略", "竞争分析"],
    category: "分析与策略",
    status: "busy",
    currentTask: "3 个任务排队",
    lastActiveAt: "刚刚",
  },
  {
    id: "xc",
    name: "小创",
    role: "创意总监",
    avatar: "XC",
    skills: ["视觉设计", "品牌创意"],
    category: "内容与创意",
    status: "idle",
    lastActiveAt: "15 分钟前",
  },
]

export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    type: "direct",
    name: "小明",
    avatar: "XM",
    members: ["xm"],
    lastMessage: "帮我分析一下竞品...",
    lastMessageTime: "10:32",
    unreadCount: 2,
  },
  {
    id: "conv-2",
    type: "direct",
    name: "小红",
    avatar: "XH",
    members: ["xh"],
    lastMessage: "文案写好了看看...",
    lastMessageTime: "10:15",
    unreadCount: 0,
  },
  {
    id: "conv-3",
    type: "group",
    name: "数据分析组",
    avatar: "GR",
    purpose: "负责数据分析和报表生成",
    members: ["xl", "xm"],
    lastMessage: "小李: Q1报告出了...",
    lastMessageSender: "小李",
    lastMessageTime: "昨天",
    unreadCount: 0,
  },
  {
    id: "conv-4",
    type: "direct",
    name: "小李",
    avatar: "XL",
    members: ["xl"],
    lastMessage: "发现个有趣的趋势...",
    lastMessageTime: "昨天",
    unreadCount: 0,
  },
  {
    id: "conv-5",
    type: "group",
    name: "产品发布小组",
    avatar: "GR",
    purpose: "策划和协调 Q2 产品发布",
    members: ["xm", "xh", "xl", "xw"],
    lastMessage: "小明: 我来整理一下...",
    lastMessageSender: "小明",
    lastMessageTime: "周一",
    unreadCount: 0,
  },
]

export const mockMessages: Record<string, Message[]> = {
  "conv-1": [
    {
      id: "msg-1",
      conversationId: "conv-1",
      senderId: "system",
      senderName: "系统",
      senderAvatar: "",
      content: "小明加入了对话",
      timestamp: "09:00",
      read: true,
      type: "system",
    },
    {
      id: "msg-2",
      conversationId: "conv-1",
      senderId: "user",
      senderName: "我（人类）",
      senderAvatar: "ZK",
      content: "小明你好，帮我分析一下智能家居市场的竞品情况",
      timestamp: "10:30",
      read: true,
      type: "text",
    },
    {
      id: "msg-3",
      conversationId: "conv-1",
      senderId: "xm",
      senderName: "小明",
      senderAvatar: "XM",
      senderRole: "产品分析师",
      content: "好的！我来帮你分析智能家居市场。请稍等...",
      timestamp: "10:31",
      read: true,
      type: "text",
    },
    {
      id: "msg-4",
      conversationId: "conv-1",
      senderId: "xm",
      senderName: "小明",
      senderAvatar: "XM",
      senderRole: "产品分析师",
      content: "这是我的分析结果：",
      timestamp: "10:32",
      read: false,
      type: "task-card",
      taskCard: {
        title: "智能家居市场竞品分析",
        progress: 60,
        scope: "市场规模、竞品、用户洞察、趋势",
        status: "in-progress",
      },
    },
  ],
  "conv-2": [
    {
      id: "msg-5",
      conversationId: "conv-2",
      senderId: "system",
      senderName: "系统",
      senderAvatar: "",
      content: "小红加入了对话",
      timestamp: "09:00",
      read: true,
      type: "system",
    },
    {
      id: "msg-6",
      conversationId: "conv-2",
      senderId: "user",
      senderName: "我（人类）",
      senderAvatar: "ZK",
      content: "小红，帮我写一篇公众号文章，主题是 AI 在日常生活中的应用",
      timestamp: "10:00",
      read: true,
      type: "text",
    },
    {
      id: "msg-7",
      conversationId: "conv-2",
      senderId: "xh",
      senderName: "小红",
      senderAvatar: "XH",
      senderRole: "文案专家",
      content: "没问题！我来撰写一篇关于 AI 日常应用的文章。初稿如下：\n\n## 《AI 如何改变我们的日常生活》\n\n从晨起的智能闹钟到晚间的娱乐推荐，AI 已经悄然融入我们生活的每一个角落...",
      timestamp: "10:15",
      read: true,
      type: "text",
    },
  ],
  "conv-5": [
    {
      id: "msg-g1",
      conversationId: "conv-5",
      senderId: "system",
      senderName: "系统",
      senderAvatar: "",
      content: "产品发布小组已创建",
      timestamp: "10:00",
      read: true,
      type: "system",
    },
    {
      id: "msg-g2",
      conversationId: "conv-5",
      senderId: "user",
      senderName: "我（人类）",
      senderAvatar: "ZK",
      content: "大家好，咱们来规划新品发布，每个人说说自己的想法",
      timestamp: "10:05",
      read: true,
      type: "text",
    },
    {
      id: "msg-g3",
      conversationId: "conv-5",
      senderId: "xm",
      senderName: "小明",
      senderAvatar: "XM",
      senderRole: "产品分析师",
      content: "好想法！根据我的分析：\n- 目标人群: 25-35岁\n- 最佳窗口: 4-5月\n\n@小红 能根据这个写个发布文案吗？",
      timestamp: "10:10",
      read: true,
      type: "text",
      mentions: ["xh"],
    },
    {
      id: "msg-g4",
      conversationId: "conv-5",
      senderId: "xh",
      senderName: "小红",
      senderAvatar: "XH",
      senderRole: "文案专家",
      content: "@小明 好的！初稿如下：\n\"发现智能生活的未来——AI融入你的日常\"",
      timestamp: "10:20",
      read: true,
      type: "text",
      mentions: ["xm"],
    },
    {
      id: "msg-g5",
      conversationId: "conv-5",
      senderId: "xl",
      senderName: "小李",
      senderAvatar: "XL",
      senderRole: "数据专家",
      content: "我拉了目标人群的最新数据：",
      timestamp: "10:35",
      read: true,
      type: "file",
      fileAttachment: {
        name: "Q1_Demographics.xlsx",
        size: "245 KB",
        type: "xlsx",
      },
    },
  ],
}

export function getAgentById(id: string): Agent | undefined {
  return mockAgents.find((a) => a.id === id)
}

export function getAgentsByIds(ids: string[]): Agent[] {
  return mockAgents.filter((a) => ids.includes(a.id))
}

export function getAgentsByCategory(): Record<string, Agent[]> {
  const result: Record<string, Agent[]> = {}
  for (const agent of mockAgents) {
    if (!result[agent.category]) {
      result[agent.category] = []
    }
    result[agent.category].push(agent)
  }
  return result
}
