import type { KnownProvider } from "./model-config-types"

export const KNOWN_PROVIDERS: KnownProvider[] = [
  // === CN ===
  {
    id: "volcengine",
    name: "Volcengine Ark",
    nameZh: "火山方舟（字节）",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    apiKeyUrl: "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
    models: ["doubao-pro-256k", "doubao-lite-128k", "deepseek-v3", "deepseek-r1"],
    category: "cn",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    nameZh: "深度求索",
    baseUrl: "https://api.deepseek.com/v1",
    apiKeyUrl: "https://platform.deepseek.com/api_keys",
    models: ["deepseek-chat", "deepseek-reasoner"],
    category: "cn",
  },
  {
    id: "siliconflow",
    name: "SiliconFlow",
    nameZh: "硅基流动",
    baseUrl: "https://api.siliconflow.cn/v1",
    apiKeyUrl: "https://cloud.siliconflow.cn/account/ak",
    models: [
      "deepseek-ai/DeepSeek-V3",
      "deepseek-ai/DeepSeek-R1",
      "Qwen/Qwen2.5-72B-Instruct",
      "THUDM/glm-4-9b-chat",
    ],
    category: "cn",
  },
  {
    id: "dashscope",
    name: "DashScope",
    nameZh: "通义千问（阿里）",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    apiKeyUrl: "https://dashscope.console.aliyun.com/apiKey",
    models: ["qwen-max", "qwen-plus", "qwen-turbo", "qwen-vl-max", "qwen-coder-plus"],
    category: "cn",
  },
  {
    id: "ernie",
    name: "Wenxin",
    nameZh: "文心一言（百度）",
    baseUrl: "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat",
    apiKeyUrl:
      "https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application",
    models: ["ernie-4.0-8k", "ernie-3.5-8k", "ernie-speed-128k", "ernie-lite-8k"],
    category: "cn",
  },
  {
    id: "hunyuan",
    name: "Hunyuan",
    nameZh: "混元（腾讯）",
    baseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
    apiKeyUrl: "https://console.cloud.tencent.com/cam/capi",
    models: ["hunyuan-pro", "hunyuan-standard", "hunyuan-lite", "hunyuan-vision"],
    category: "cn",
  },
  {
    id: "zhipu",
    name: "Zhipu AI",
    nameZh: "智谱清言（GLM）",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    apiKeyUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    models: ["glm-4-plus", "glm-4", "glm-4-flash", "glm-4v-plus"],
    category: "cn",
  },
  {
    id: "yi",
    name: "Yi / Lingyiwanwu",
    nameZh: "零一万物",
    baseUrl: "https://api.lingyiwanwu.com/v1",
    apiKeyUrl: "https://platform.lingyiwanwu.com/apikeys",
    models: ["yi-large", "yi-medium", "yi-small", "yi-vision"],
    category: "cn",
  },
  {
    id: "minimax",
    name: "MiniMax",
    nameZh: "MiniMax",
    baseUrl: "https://api.minimax.chat/v1",
    apiKeyUrl: "https://platform.minimaxi.com/user-center/basic-information/interface-key",
    models: ["MiniMax-Text-01", "abab6.5s-chat", "abab5.5-chat"],
    category: "cn",
  },
  {
    id: "spark",
    name: "Spark",
    nameZh: "星火（讯飞）",
    baseUrl: "https://spark-api-open.xf-yun.com/v1",
    apiKeyUrl: "https://console.xfyun.cn/services/bm35",
    models: ["spark-pro-128k", "spark-lite", "spark-max"],
    category: "cn",
  },
  // === Intl ===
  {
    id: "openai",
    name: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    apiKeyUrl: "https://platform.openai.com/api-keys",
    models: ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "o1", "o1-mini", "o3-mini"],
    category: "intl",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    apiType: "anthropic-messages",
    apiKeyUrl: "https://console.anthropic.com/settings/keys",
    models: ["claude-sonnet-4-5", "claude-haiku-3-5", "claude-3-opus"],
    category: "intl",
  },
  {
    id: "google",
    name: "Google Gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    apiType: "google-generative-ai",
    apiKeyUrl: "https://aistudio.google.com/app/apikey",
    models: ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.0-flash", "gemini-1.5-pro"],
    category: "intl",
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    baseUrl: "https://api.x.ai/v1",
    apiKeyUrl: "https://console.x.ai/",
    models: ["grok-3", "grok-3-mini", "grok-2"],
    category: "intl",
  },
  {
    id: "groq",
    name: "Groq",
    baseUrl: "https://api.groq.com/openai/v1",
    apiKeyUrl: "https://console.groq.com/keys",
    models: ["llama-3.3-70b-versatile", "mixtral-8x7b-32768", "gemma2-9b-it"],
    category: "intl",
  },
  // === Aggregation ===
  {
    id: "openrouter",
    name: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    apiKeyUrl: "https://openrouter.ai/keys",
    models: [
      "anthropic/claude-sonnet-4-5",
      "openai/gpt-4o",
      "google/gemini-2.5-pro",
      "deepseek/deepseek-r1",
    ],
    category: "agg",
  },
  {
    id: "together",
    name: "Together AI",
    baseUrl: "https://api.together.xyz/v1",
    apiKeyUrl: "https://api.together.xyz/settings/api-keys",
    models: [
      "meta-llama/Llama-3.3-70B-Instruct-Turbo",
      "Qwen/Qwen2.5-72B-Instruct-Turbo",
    ],
    category: "agg",
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    apiKeyUrl: "https://build.nvidia.com/models",
    models: ["meta/llama-3.1-405b-instruct", "minimaxai/minimax-m2.1"],
    category: "agg",
  },
]
